/**
 * Créée le 18 août 08
 */
package com.util.sql;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * @author LhaaG
 *
 */
public class SQLManager {

	static Connection connexion;

	public static void init() {
		try {
			Class.forName("org.hsqldb.jdbcDriver").newInstance();
		} catch (InstantiationException e) {
			e.printStackTrace();
		} catch (IllegalAccessException e) {
			e.printStackTrace();
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
		}

		try {
			connexion = DriverManager.getConnection("jdbc:hsqldb:file:data/jigolo", "sa",  "");

		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	public static void close() {
		try {
			Statement statement = connexion.createStatement();
			statement.executeQuery("SHUTDOWN");
			statement.close();
			connexion.close();
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	public static void createTables() {
		try {
			Statement statement = connexion.createStatement() ;

			// account
			statement.executeUpdate("CREATE TABLE account (id INT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY, pseudo VARCHAR(100), pwd VARCHAR(40), short_desc VARCHAR(300), init_date TIMESTAMP)");

			// school
			statement.executeUpdate("CREATE TABLE school (id INT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY, name VARCHAR(100), slogan VARCHAR(255))");

			// skill
			statement.executeUpdate("CREATE TABLE skill (id INT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY, name VARCHAR(100), level INT, description VARCHAR(255), family VARCHAR(100))");
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

}// class SQLManager